package generators

import (
	"encoding/json"
	"fmt"
	"math"
	"strings"

	rainbeau "github.com/AlexMacocian/rainbeau/internal"
)

type HyprchatGenerator struct{}

func (HyprchatGenerator) Name() string       { return "HyprChat" }
func (HyprchatGenerator) OutputPath() string { return ".config/hyprchat/theme.jsonc" }
func (HyprchatGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	fnt := theme.Font
	dangerBg := rainbeau.MixColors(p.Red, c.Bg0, 0.25)
	return fmt.Sprintf(`// Auto-generated by Rainbeau — do not edit manually
// Theme: %s
{
  "bg0": "%s",
  "bg1": "%s",
  "bg2": "%s",
  "bg3": "%s",
  "border": "%s",
  "accent1": "%s",
  "accent2": "%s",
  "text": "%s",
  "textDim": "%s",
  "danger": "%s",
  "dangerBg": "%s",
  "fontFamily": "%s",
  "fontSize": %d
}
`, theme.Name, c.Bg0, c.Bg1, c.Bg2, c.Bg3, p.Border, p.Accent1, p.Accent2, p.Text, p.TextDim, p.Red, dangerBg, fnt.Family, fnt.Size+2), nil
}

type HyprtoolkitGenerator struct{}

func (HyprtoolkitGenerator) Name() string       { return "Hyprtoolkit" }
func (HyprtoolkitGenerator) OutputPath() string { return ".config/hypr/hyprtoolkit.conf" }
func (HyprtoolkitGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	fnt := theme.Font
	h := theme.Hyprland
	return fmt.Sprintf(`# Auto-generated by Rainbeau — do not edit manually
# Theme: %s

background = 0xFF%s
base = 0xFF%s
text = 0xFF%s
alternate_base = 0xFF%s
bright_text = 0xFF%s
accent = 0xFF%s
accent_secondary = 0xFF%s

font_family = %s
font_family_monospace = %s
font_size = 13
h1_size = 19
h2_size = 15
h3_size = 13
small_font_size = 10

rounding_large = %d
rounding_small = %d
`, theme.Name, stripHash(c.Bg0), stripHash(c.Bg1), stripHash(p.Text), stripHash(c.Bg2), stripHash(p.Accent1), stripHash(p.Border), stripHash(p.Accent2), fnt.Family, fnt.Family, h.Rounding+4, h.Rounding), nil
}

type OmniLauncherConfigGenerator struct{}

func (OmniLauncherConfigGenerator) Name() string       { return "Omni Launcher Config" }
func (OmniLauncherConfigGenerator) OutputPath() string { return ".config/omni-launcher/config.json" }

func (OmniLauncherConfigGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	fnt := theme.Font
	selectedBg := rainbeau.MixColors(p.Accent1, c.Bg0, 0.72)
	config := map[string]any{
		"fontFamily":  fnt.Family,
		"fontSize":    int(math.Max(14, float64(fnt.Size+4))),
		"giphyApiKey": "",
		"panelWidth":  720,
		"panelHeight": 520,
		"padding":     5,
		"spacing":     5,
		"radius":      int(math.Max(6, float64(theme.Hyprland.Rounding*2))),
		"colors": map[string]any{
			"background":    c.Bg0,
			"foreground":    p.Text,
			"idle":          p.TextDim,
			"accent":        p.Accent1,
			"overlayStrong": selectedBg,
			"overlayWeak":   c.Bg2,
			"border":        p.Border,
		},
	}
	content, err := json.MarshalIndent(config, "", "  ")
	return string(content) + "\n", err
}

type QuickVisorThemeGenerator struct{}

func (QuickVisorThemeGenerator) Name() string       { return "Quick Visor Theme" }
func (QuickVisorThemeGenerator) OutputPath() string { return ".config/quick-visor/theme.jsonc" }
func (QuickVisorThemeGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	fnt := theme.Font
	config := map[string]any{
		"fontFamily":    fnt.Family,
		"fontSize":      int(math.Max(12, float64(fnt.Size+2))),
		"background":    c.Bg0,
		"foreground":    p.Text,
		"idle":          p.TextDim,
		"accent":        p.Accent1,
		"warning":       p.Red,
		"overlayStrong": p.SelectionBg,
		"overlayWeak":   c.Bg2,
		"border":        p.Border,
		"padding":       int(math.Max(6, float64(theme.Hyprland.GapsIn))),
		"spacing":       int(math.Max(6, float64(theme.Hyprland.GapsIn))),
		"radius":        int(math.Max(8, float64(theme.Hyprland.Rounding*2))),
	}
	content, err := json.MarshalIndent(config, "", "  ")
	return fmt.Sprintf("// Auto-generated by Rainbeau — do not edit manually\n// Theme: %s\n%s\n", theme.Name, content), err
}

type FirefoxThemeGenerator struct{}

func (FirefoxThemeGenerator) Name() string       { return "Firefox Theme" }
func (FirefoxThemeGenerator) OutputPath() string { return ".config/firefox-theme/theme-colors.json" }

func (FirefoxThemeGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	colorScheme := "dark"
	if p.IsLight {
		colorScheme = "light"
	}
	content := map[string]any{
		"colors": map[string]string{
			"frame":                        c.Bg0,
			"frame_inactive":               c.Bg0,
			"tab_background_text":          p.Text,
			"tab_selected":                 c.Bg1,
			"tab_line":                     p.Border,
			"tab_loading":                  p.Border,
			"toolbar":                      c.Bg0,
			"toolbar_text":                 p.Text,
			"toolbar_field":                c.Bg1,
			"toolbar_field_text":           p.Text,
			"toolbar_field_border":         p.Inactive,
			"toolbar_field_border_focus":   p.Border,
			"toolbar_field_highlight":      p.SelectionBg,
			"toolbar_field_highlight_text": p.SelectionFg,
			"toolbar_bottom_separator":     c.Bg2,
			"toolbar_top_separator":        c.Bg2,
			"toolbar_vertical_separator":   c.Bg2,
			"popup":                        c.Bg1,
			"popup_text":                   p.Text,
			"popup_border":                 c.Bg2,
			"popup_highlight":              p.SelectionBg,
			"popup_highlight_text":         p.SelectionFg,
			"sidebar":                      c.Bg0,
			"sidebar_text":                 p.Text,
			"sidebar_border":               c.Bg2,
			"sidebar_highlight":            p.SelectionBg,
			"sidebar_highlight_text":       p.SelectionFg,
			"ntp_background":               c.Bg0,
			"ntp_card_background":          c.Bg1,
			"ntp_text":                     p.Text,
			"button_background_hover":      c.Bg1,
			"button_background_active":     c.Bg2,
			"icons":                        p.TextDim,
			"icons_attention":              p.Border,
		},
		"properties": map[string]string{
			"color_scheme":         colorScheme,
			"content_color_scheme": colorScheme,
		},
	}
	bytes, err := json.MarshalIndent(content, "", "  ")
	return string(bytes) + "\n", err
}

type FirefoxPrefsGenerator struct{}

func (FirefoxPrefsGenerator) Name() string       { return "Firefox Prefs" }
func (FirefoxPrefsGenerator) OutputPath() string { return ".config/firefox-theme/user-prefs.js" }
func (FirefoxPrefsGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	override := "0"
	if strings.Contains(strings.ToLower(theme.Gtk.ColorScheme), "light") {
		override = "1"
	}
	return fmt.Sprintf(`// Auto-generated by Rainbeau — do not edit manually
// Theme: %s
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("layout.css.prefers-color-scheme.content-override", %s);
`, theme.Name, override), nil
}

type FirefoxContentGenerator struct{}

func (FirefoxContentGenerator) Name() string       { return "Firefox Content" }
func (FirefoxContentGenerator) OutputPath() string { return ".config/firefox-theme/userContent.css" }

func (FirefoxContentGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	return replaceTokens(`/* Auto-generated by Rainbeau — do not edit manually */
/* Theme: @@theme@@ */
/* Styles web page content (links, new tab page, etc.) */

@-moz-document url-prefix("http"), url-prefix("https"), url-prefix("file"), url-prefix("about") {
    ::selection {
        background-color: @@border@@ !important;
        color: @@bg0@@ !important;
    }

    ::-moz-selection {
        background-color: @@border@@ !important;
        color: @@bg0@@ !important;
    }
}

@-moz-document url-prefix("http"), url-prefix("https"), url-prefix("file") {
    a:link { color: @@accent1@@ !important; }
    a:visited { color: @@accent2@@ !important; }
    a:hover { color: @@border@@ !important; }
    a:active { color: @@text@@ !important; }
}

@-moz-document url("about:home"), url("about:newtab"), url("about:privatebrowsing") {
    .search-wrapper input {
        background-color: @@bg1@@ !important;
        color: @@text@@ !important;
        border: 1px solid @@inactive@@ !important;
    }

    .search-wrapper input:focus {
        border-color: @@border@@ !important;
    }
}

@-moz-document url("about:blank") {
    body {
        background-color: @@bg0@@ !important;
    }
}
`, map[string]string{
		"theme":    theme.Name,
		"border":   c.Border,
		"bg0":      c.Bg0,
		"bg1":      c.Bg1,
		"accent1":  c.Accent1,
		"accent2":  c.Accent2,
		"text":     c.Text,
		"inactive": c.Inactive,
	}), nil
}

type FirefoxGenerator struct{}

func (FirefoxGenerator) Name() string       { return "Firefox" }
func (FirefoxGenerator) OutputPath() string { return ".config/firefox-theme/userChrome.css" }
func (FirefoxGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	return replaceTokens(`/* Auto-generated by Rainbeau — do not edit manually */
/* Theme: @@theme@@ */
/* Colors are driven by the Theme API (browser.theme.update) at runtime. */
/* This CSS references --lwt-* variables so it auto-updates when the theme changes. */

:root {
    --er-bg0: var(--lwt-accent-color, @@bg0@@);
    --er-bg1: var(--lwt-toolbar-field-background-color, @@bg1@@);
    --er-bg2: var(--arrowpanel-border-color, @@bg2@@);
    --er-bg3: @@bg3@@;
    --er-border: var(--lwt-toolbar-field-focus-border-color, @@border@@);
    --er-accent1: @@accent1@@;
    --er-accent2: @@accent2@@;
    --er-text: var(--lwt-text-color, @@text@@);
    --er-text-dim: @@textDim@@;
    --er-inactive: var(--lwt-toolbar-field-border-color, @@inactive@@);
    --er-red: @@red@@;
}

#TabsToolbar { background-color: var(--er-bg0) !important; }
.tabbrowser-tab .tab-background {
    background-color: var(--er-bg0) !important;
    border: none !important;
}
.tabbrowser-tab[selected] .tab-background {
    background-color: var(--er-bg1) !important;
    border-bottom: 2px solid var(--er-border) !important;
}
.tabbrowser-tab .tab-label { color: var(--er-text-dim) !important; }
.tabbrowser-tab[selected] .tab-label { color: var(--er-text) !important; }
.tabbrowser-tab:hover:not([selected]) .tab-background { background-color: var(--er-bg1) !important; }

#nav-bar {
    background-color: var(--er-bg0) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}

#urlbar-background {
    background-color: var(--er-bg1) !important;
    border: 1px solid var(--er-inactive) !important;
    border-radius: 4px !important;
}
#urlbar:hover #urlbar-background,
#urlbar[focused] #urlbar-background { border-color: var(--er-border) !important; }
#urlbar-input { color: var(--er-text) !important; }

#nav-bar toolbarbutton,
#TabsToolbar toolbarbutton,
#nav-bar toolbarbutton image,
#TabsToolbar toolbarbutton image {
    fill: var(--er-text-dim) !important;
    color: var(--er-text-dim) !important;
}

#nav-bar toolbarbutton:hover,
#TabsToolbar toolbarbutton:hover {
    background-color: var(--er-bg1) !important;
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
    border-radius: 4px !important;
}

#nav-bar toolbarbutton:hover image,
#TabsToolbar toolbarbutton:hover image {
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
}

#nav-bar toolbarbutton:active,
#TabsToolbar toolbarbutton:active { background-color: var(--er-bg2) !important; }

#PersonalToolbar {
    background-color: var(--er-bg0) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}
#PlacesToolbarItems toolbarbutton { color: var(--er-text-dim) !important; }
#PlacesToolbarItems toolbarbutton:hover {
    background-color: var(--er-bg1) !important;
    color: var(--er-accent1) !important;
}

#sidebar-header {
    background-color: var(--er-bg1) !important;
    color: var(--er-text) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}
#sidebar-box,
#sidebar-main,
#sidebar-launcher { background-color: var(--er-bg0) !important; }
#sidebar-main { color: var(--er-text) !important; }

#sidebar-launcher toolbarbutton,
#sidebar-launcher .sidebar-launcher-button {
    fill: var(--er-text-dim) !important;
    color: var(--er-text-dim) !important;
}
#sidebar-launcher toolbarbutton:hover,
#sidebar-launcher .sidebar-launcher-button:hover {
    background-color: var(--er-bg1) !important;
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
}
#sidebar-launcher toolbarbutton[checked],
#sidebar-launcher .sidebar-launcher-button[active] {
    background-color: var(--er-bg1) !important;
    fill: var(--er-border) !important;
    color: var(--er-border) !important;
}

#sidebar-splitter {
    border-color: var(--er-bg2) !important;
    background-color: var(--er-bg2) !important;
}
#sidebar-splitter:hover {
    border-color: var(--er-border) !important;
    background-color: var(--er-border) !important;
}

*:focus-visible { outline-color: var(--er-border) !important; }
::selection {
    background-color: var(--er-border) !important;
    color: var(--er-bg0) !important;
}

findbar {
    background-color: var(--er-bg1) !important;
    border-top: 1px solid var(--er-bg2) !important;
    color: var(--er-text) !important;
}

.autocomplete-richlistbox {
    background-color: var(--er-bg1) !important;
    color: var(--er-text) !important;
}
.autocomplete-richlistitem:hover { background-color: var(--er-bg2) !important; }
#tabs-newtab-button:hover { background-color: var(--er-bg1) !important; }
.tab-close-button:hover {
    background-color: var(--er-red) !important;
    border-radius: 50%;
}
`, map[string]string{
		"theme":    theme.Name,
		"bg0":      c.Bg0,
		"bg1":      c.Bg1,
		"bg2":      c.Bg2,
		"bg3":      c.Bg3,
		"border":   c.Border,
		"accent1":  c.Accent1,
		"accent2":  c.Accent2,
		"text":     c.Text,
		"textDim":  c.TextDim,
		"inactive": c.Inactive,
		"red":      c.Red,
	}), nil
}
