package generators

import (
	"fmt"
	"math/rand"
	"strings"

	rainbeau "github.com/AlexMacocian/rainbeau/internal"
)

type HyprlandGenerator struct{}

func (HyprlandGenerator) Name() string       { return "Hyprland" }
func (HyprlandGenerator) OutputPath() string { return ".config/hypr/theme.conf" }
func (HyprlandGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	h := theme.Hyprland
	return fmt.Sprintf(`# Auto-generated by Rainbeau — do not edit manually
# Theme: %s

general {
    gaps_in = %d
    gaps_out = %d
    border_size = %d
    col.active_border = rgba(%s) rgba(%s) 45deg
    col.inactive_border = rgba(%s)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = %d
    rounding_power = 2
    active_opacity = %s
    inactive_opacity = %s

    shadow {
        enabled = true
        range = %d
        render_power = %d
        color = rgba(%s)
    }

    blur {
        enabled = true
        size = %d
        passes = %d
        vibrancy = %s
    }
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = global,        1,     %s,    default
    animation = border,        1,     %s,     easeOutQuint
    animation = windows,       1,     %s,   easeOutQuint
    animation = windowsIn,     1,     %s,     easeOutQuint, popin 87%%
    animation = windowsOut,    1,     %s,     linear,       popin 87%%
    animation = fadeIn,        1,     %s,   almostLinear
    animation = fadeOut,       1,     %s,     almostLinear
    animation = fade,          1,     3.5,   quick
    animation = layers,        1,     4.5,   easeOutQuint
    animation = layersIn,      1,     4.5,   easeOutQuint, fade
    animation = layersOut,     1,     2,     linear,       fade
    animation = fadeLayersIn,  1,     2.5,   almostLinear
    animation = fadeLayersOut, 1,     1.8,   almostLinear
    animation = workspaces,    1,     %s,     almostLinear, fade
    animation = workspacesIn,  1,     2,     almostLinear, fade
    animation = workspacesOut, 1,     %s,     almostLinear, fade
    animation = zoomFactor,    1,     8,     quick
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    background_color = rgb(%s)
    vrr = 0
}

# GTK theme for GTK4 apps (Nautilus, etc.)
env = GTK_THEME,%s
`, theme.Name, h.GapsIn, h.GapsOut, h.BorderSize, rainbeau.ToHyprRgba(c.Border), rainbeau.ToHyprRgba(c.Accent2), rainbeau.ToHyprRgba(c.Inactive, "aa"), h.Rounding, f(h.ActiveOpacity), f(h.InactiveOpacity), h.ShadowRange, h.ShadowRenderPower, rainbeau.ToHyprRgba(c.Bg1), h.BlurSize, h.BlurPasses, f(h.BlurVibrancy), f(h.AnimationSpeedGlobal), f(h.AnimationSpeedBorder), f(h.AnimationSpeedWindows), f(h.AnimationSpeedWindowsIn), f(h.AnimationSpeedWindowsOut), f(h.AnimationSpeedFadeIn), f(h.AnimationSpeedFadeOut), f(h.AnimationSpeedWorkspaces), f(h.AnimationSpeedWorkspaces), strings.TrimPrefix(c.Bg0, "#"), theme.Gtk.Theme), nil
}

type HyprpaperGenerator struct{}

func (HyprpaperGenerator) Name() string       { return "Hyprpaper" }
func (HyprpaperGenerator) OutputPath() string { return ".config/hypr/hyprpaper.conf" }
func (HyprpaperGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	images := theme.Wallpapers.Images
	if len(images) == 0 {
		return fmt.Sprintf(`# Auto-generated by Rainbeau — do not edit manually
# Theme: %s
# (No static images; wallpaper handled by mpvpaper.)

splash = false
ipc = true
`, theme.Name), nil
	}
	pick := images[rand.Intn(len(images))]
	var preloads []string
	for _, image := range images {
		preloads = append(preloads, fmt.Sprintf("preload = ~/.config/hypr/wallpapers/%s", image))
	}
	return fmt.Sprintf(`# Auto-generated by Rainbeau — do not edit manually
# Theme: %s

%s

wallpaper {
    monitor =
    path = ~/.config/hypr/wallpapers/%s
}

splash = false
ipc = true
`, theme.Name, strings.Join(preloads, "\n"), pick), nil
}

type DunstGenerator struct{}

func (DunstGenerator) Name() string       { return "Dunst" }
func (DunstGenerator) OutputPath() string { return ".config/dunst/dunstrc" }
func (DunstGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	font := theme.Font
	return fmt.Sprintf(`# Auto-generated by Rainbeau — do not edit manually
# Theme: %s

[global]
    monitor = 0
    follow = mouse
    width = 350
    height = 120
    origin = top-right
    offset = 20x20
    notification_limit = 5
    progress_bar = true
    indicate_hidden = yes
    transparency = 0
    separator_height = 2
    padding = 12
    horizontal_padding = 16
    text_icon_padding = 16
    frame_width = 2
    frame_color = "%s"
    gap_size = 6
    separator_color = frame
    sort = yes
    font = %s 11
    line_height = 0
    markup = full
    format = "<b>%%s</b>\n%%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes
    icon_position = left
    min_icon_size = 32
    max_icon_size = 64
    corner_radius = 4
    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all

[urgency_low]
    background = "%s"
    foreground = "%s"
    frame_color = "%s"
    timeout = 5

[urgency_normal]
    background = "%s"
    foreground = "%s"
    frame_color = "%s"
    timeout = 10

[urgency_critical]
    background = "%s"
    foreground = "%s"
    frame_color = "%s"
    timeout = 0
`, theme.Name, p.Border, font.Family, c.Bg1, p.TextDim, p.Inactive, c.Bg1, p.Text, p.Border, c.Bg1, p.Text, p.Red), nil
}

type GtkSettingsGenerator struct{}

func (GtkSettingsGenerator) Name() string       { return "GTK Settings" }
func (GtkSettingsGenerator) OutputPath() string { return ".config/gtk-3.0/settings.ini" }
func (GtkSettingsGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	return fmt.Sprintf(`# Auto-generated by Rainbeau
# Theme: %s
[Settings]
gtk-application-prefer-dark-theme=1
gtk-theme-name=%s
gtk-font-name=%s 11
gtk-cursor-theme-size=24
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
`, theme.Name, theme.Gtk.Theme, theme.Font.Family), nil
}

type KittyGenerator struct{}

func (KittyGenerator) Name() string       { return "Kitty" }
func (KittyGenerator) OutputPath() string { return ".config/kitty/kitty.conf" }
func (KittyGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	font := theme.Font
	p := rainbeau.ResolvePalette(theme)
	return fmt.Sprintf(`# Auto-generated by Rainbeau — do not edit manually
# Theme: %s

# Font
font_family %s
font_size %d

# Colors
foreground %s
background %s

# Selection — high-contrast pair so highlighted text is always visible,
# even when the terminal window is translucent and a busy wallpaper is
# bleeding through.
selection_foreground %s
selection_background %s

cursor %s
cursor_text_color %s
url_color %s

# Window
background_opacity %s
window_padding_width 8
window_margin_width 0
hide_window_decorations yes
confirm_os_window_close 0

# Remote control (needed for live theme reload)
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

# Tab bar
active_tab_foreground %s
active_tab_background %s
active_tab_font_style bold
inactive_tab_foreground %s
inactive_tab_background %s
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Terminal bell
enable_audio_bell no
visual_bell_duration 0

# ANSI colors — every slot is contrast-checked (WCAG AAA against the
# background) and perceptually distinct from its neighbors.
# black (used as dark foreground/background by TUIs)
color0 %s
color8 %s

# red
color1 %s
color9 %s

# green
color2 %s
color10 %s

# yellow
color3 %s
color11 %s

# blue
color4 %s
color12 %s

# magenta
color5 %s
color13 %s

# cyan
color6 %s
color14 %s

# white (used as light foreground/background by TUIs)
color7 %s
color15 %s
`, theme.Name, font.Family, font.Size-2, p.Text, p.Bg0, p.SelectionFg, p.SelectionBg, p.Border, p.Bg0, p.Accent1, f(theme.Terminal.EffectiveOpacity()), p.Accent1, p.Bg1, p.TextDim, p.Bg0, p.AnsiBlack, p.BrightBlack, p.AnsiRed, p.BrightRed, p.AnsiGreen, p.BrightGreen, p.AnsiYellow, p.BrightYellow, p.AnsiBlue, p.BrightBlue, p.AnsiMagenta, p.BrightMagenta, p.AnsiCyan, p.BrightCyan, p.AnsiWhite, p.BrightWhite), nil
}

type WofiStyleGenerator struct{}

func (WofiStyleGenerator) Name() string       { return "Wofi Style" }
func (WofiStyleGenerator) OutputPath() string { return ".config/wofi/style.css" }
func (WofiStyleGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	font := theme.Font
	return fmt.Sprintf(`/* Auto-generated by Rainbeau — do not edit manually */
/* Theme: %s */

window {
    margin: 0;
    border: 2px solid %s;
    border-radius: 8px;
    background-color: %s;
    font-family: "%s";
    font-size: 14px;
}

#input {
    margin: 8px;
    padding: 8px 12px;
    border: none;
    border-bottom: 2px solid %s;
    border-radius: 4px;
    background-color: %s;
    color: %s;
    font-size: 14px;
}

#input:focus {
    border-bottom-color: %s;
}

#inner-box {
    margin: 4px;
}

#outer-box {
    margin: 0;
    padding: 0;
}

#scroll {
    margin: 0;
}

#text {
    margin: 0;
    padding: 6px 12px;
    color: %s;
    background: transparent;
    min-width: 100%%;
}

#entry {
    padding: 0;
    margin: 2px 4px;
    border-radius: 4px;
    background: transparent;
}

#entry * {
    background: transparent;
}

#entry:selected,
#entry:selected * {
    background-color: %s;
}

#entry:selected:active,
#entry:selected:active * {
    background-color: %s;
}

#entry:selected #text,
#entry:selected:active #text {
    color: %s;
    font-weight: bold;
}
`, theme.Name, p.Border, c.Bg0, font.Family, c.Bg2, c.Bg1, p.Text, p.Border, p.Text, p.SelectionBg, p.SelectionBg, p.SelectionFg), nil
}

type BluetoothScriptGenerator struct{}

func (BluetoothScriptGenerator) Name() string { return "Bluetooth Script" }
func (BluetoothScriptGenerator) OutputPath() string {
	return ".config/hypr/scripts/bluetooth-status.sh"
}

func (BluetoothScriptGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	sep := theme.Waybar.Separator
	return fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by Rainbeau — do not edit manually
# Theme: %s
# Bluetooth status for waybar custom module

ICON=$'\uf294'
SEP="<span color='%s'>%s</span>"

powered=$(bluetoothctl show 2>/dev/null | grep -c "Powered: yes")
if [[ "$powered" -eq 0 ]]; then
    printf '{"text": "%%s off %%s", "tooltip": "Bluetooth off", "class": "off"}\n' "$ICON" "$SEP"
    exit 0
fi

connected=$(bluetoothctl devices Connected 2>/dev/null)
if [[ -n "$connected" ]]; then
    device_name=$(echo "$connected" | head -1 | cut -d' ' -f3-)
    count=$(echo "$connected" | wc -l)
    if [[ "$count" -gt 1 ]]; then
        printf '{"text": "%%s %%s %%s", "tooltip": "%%s devices connected", "class": "connected"}\n' "$ICON" "$count" "$SEP" "$count"
    else
        printf '{"text": "%%s %%s %%s", "tooltip": "Connected: %%s", "class": "connected"}\n' "$ICON" "$device_name" "$SEP" "$device_name"
    fi
else
    printf '{"text": "%%s on %%s", "tooltip": "Bluetooth on, no devices", "class": "on"}\n' "$ICON" "$SEP"
fi
`, theme.Name, c.Accent1, sep), nil
}

type GpuScriptGenerator struct{}

func (GpuScriptGenerator) Name() string       { return "GPU Script" }
func (GpuScriptGenerator) OutputPath() string { return ".config/hypr/scripts/gpu-usage.sh" }
func (GpuScriptGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	sep := theme.Waybar.Separator
	return fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by Rainbeau — do not edit manually
# Theme: %s
# Auto-detected GPU usage for waybar

ICON=$'\uf26c'
SEP="<span color='%s'>%s</span>"

get_nvidia() {
    if command -v nvidia-smi &>/dev/null; then
        usage=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
        if [[ -n "$usage" ]]; then
            printf '{"text": "%%s %%s%%%% %%s", "tooltip": "NVIDIA GPU: %%s%%%%", "class": "nvidia"}\n' "$ICON" "$usage" "$SEP" "$usage"
            return 0
        fi
    fi
    return 1
}

get_amd() {
    for gpu in /sys/class/drm/card*/device/gpu_busy_percent; do
        if [[ -r "$gpu" ]]; then
            usage=$(cat "$gpu" 2>/dev/null)
            if [[ -n "$usage" ]]; then
                printf '{"text": "%%s %%s%%%% %%s", "tooltip": "AMD GPU: %%s%%%%", "class": "amd"}\n' "$ICON" "$usage" "$SEP" "$usage"
                return 0
            fi
        fi
    done
    return 1
}

get_nvidia || get_amd || printf '{"text": "%%s N/A %%s", "tooltip": "No GPU detected", "class": "none"}\n' "$ICON" "$SEP"
`, theme.Name, c.Accent1, sep), nil
}

func f(value float64) string {
	return strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.6f", value), "0"), ".")
}
