package generators

import (
	"strings"
	"testing"

	rainbeau "github.com/AlexMacocian/rainbeau/internal"
)

// The Hyprland generator is one big fmt.Sprintf with ~27 verbs fed by a single
// positional argument list. Reordering the template without reordering the
// arguments shifts every later value by one slot, and because almost all of
// them are %s fed by strings, neither the compiler nor `go vet` notices. The
// symptom is a config that still looks plausible — e.g. a colour landing in an
// animation speed (`speed = 1c1c1c`).
//
// This test pins distinct, mutually-unmistakable values to every field so any
// such shift shows up as a concrete mismatch rather than a subtle theming bug.
func TestHyprlandGeneratorPlacesValuesInTheRightFields(t *testing.T) {
	theme := &rainbeau.Theme{Name: "TestTheme"}
	theme.Colors = rainbeau.ThemeColors{
		Bg0:      "#010203",
		Bg1:      "#040506",
		Border:   "#070809",
		Accent2:  "#0a0b0c",
		Inactive: "#0d0e0f",
	}
	theme.Hyprland = rainbeau.HyprlandSettings{
		GapsIn:                   11,
		GapsOut:                  12,
		BorderSize:               13,
		Rounding:                 14,
		ShadowRange:              15,
		ShadowRenderPower:        16,
		BlurSize:                 17,
		BlurPasses:               18,
		BlurVibrancy:             0.19,
		ActiveOpacity:            0.21,
		InactiveOpacity:          0.22,
		AnimationSpeedGlobal:     31,
		AnimationSpeedBorder:     32,
		AnimationSpeedWindows:    33,
		AnimationSpeedWindowsIn:  34,
		AnimationSpeedWindowsOut: 35,
		AnimationSpeedFadeIn:     36,
		AnimationSpeedFadeOut:    37,
		AnimationSpeedWorkspaces: 38,
	}
	theme.Gtk.Theme = "TestGtkTheme"

	out, err := HyprlandGenerator{}.Generate(theme, "")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	for _, want := range []string{
		"-- Theme: TestTheme",
		"gaps_in     = 11,",
		"gaps_out    = 12,",
		"border_size = 13,",
		`active_border   = { colors = { "rgba(070809ee)", "rgba(0a0b0cee)" }, angle = 45 }`,
		`inactive_border = "rgba(0d0e0faa)"`,
		"rounding         = 14,",
		"active_opacity   = 0.21,",
		"inactive_opacity = 0.22,",
		"range        = 15,",
		"render_power = 16,",
		`color        = "rgba(040506ee)"`,
		"size     = 17,",
		"passes   = 18,",
		"vibrancy = 0.19,",
		`background_color        = "rgb(010203)"`,
		`leaf = "global",        enabled = true, speed = 31,`,
		`leaf = "border",        enabled = true, speed = 32,`,
		`leaf = "windows",       enabled = true, speed = 33,`,
		`leaf = "windowsIn",     enabled = true, speed = 34,`,
		`leaf = "windowsOut",    enabled = true, speed = 35,`,
		`leaf = "fadeIn",        enabled = true, speed = 36,`,
		`leaf = "fadeOut",       enabled = true, speed = 37,`,
		`leaf = "workspaces",    enabled = true, speed = 38,`,
		`leaf = "workspacesOut", enabled = true, speed = 38,`,
		`hl.env("GTK_THEME", "TestGtkTheme")`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated config missing expected fragment:\n  %s", want)
		}
	}
}

// Hyprland loads this file as Lua, so the old hyprlang syntax must be fully
// gone. A stray `key = value` line or a `#` comment would be a syntax error
// that takes down the whole config at startup.
func TestHyprlandGeneratorEmitsLuaNotHyprlang(t *testing.T) {
	theme := &rainbeau.Theme{Name: "TestTheme"}
	theme.Gtk.Theme = "Adwaita-dark"

	out, err := HyprlandGenerator{}.Generate(theme, "")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if got := (HyprlandGenerator{}).OutputPath(); got != ".config/hypr/theme.lua" {
		t.Errorf("OutputPath = %q, want .config/hypr/theme.lua", got)
	}

	// These are hyprlang statements, which always begin a line. The same words
	// appear mid-line as Lua table keys (e.g. `bezier = "default"` inside an
	// hl.animation{...} call), so anchor on the start of the trimmed line.
	for _, line := range strings.Split(out, "\n") {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "#") {
			t.Errorf("generated config contains a hyprlang '#' comment: %q", line)
		}

		for _, forbidden := range []string{
			"bezier =",    // hyprlang curve syntax, now hl.curve(...)
			"animation =", // hyprlang animation syntax, now hl.animation{...}
			"env =",       // hyprlang env syntax, now hl.env(...)
		} {
			if strings.HasPrefix(trimmed, forbidden) {
				t.Errorf("generated config still contains hyprlang syntax %q: %q", forbidden, line)
			}
		}
	}

	// hyprlang-only boolean spelling; invalid as Lua anywhere in the file.
	if strings.Contains(out, "yes, please :)") {
		t.Error(`generated config still contains the hyprlang "yes, please :)" boolean`)
	}

	if !strings.HasPrefix(out, "-- Auto-generated by Rainbeau") {
		t.Error("generated config does not start with a Lua comment header")
	}
}
