package generators

import (
	"fmt"
	"math/rand"
	"path/filepath"
	"strings"

	rainbeau "github.com/AlexMacocian/rainbeau/internal"
)

type WallpaperCyclerGenerator struct{}

func (WallpaperCyclerGenerator) Name() string { return "Wallpaper Cycler" }
func (WallpaperCyclerGenerator) OutputPath() string {
	return ".config/hypr/scripts/wallpaper-cycler.sh"
}

func (WallpaperCyclerGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	imageEntries := wallpaperArrayEntries(theme.Wallpapers.Images, false)
	videoEntries := wallpaperArrayEntries(theme.Wallpapers.Videos, true)
	return fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by Rainbeau — do not edit manually
# Theme: %s
# Cycles wallpapers (images and videos) from the theme's wallpaper lists
# Usage: wallpaper-cycler.sh [interval_seconds]
# Default interval: %d seconds

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"
INTERVAL="${1:-%d}"
FIT_MODE="%s"

IMAGES=(
%s
)

VIDEOS=(
%s
)

# Build list of valid entries based on available tools
ENTRIES=()
if command -v hyprpaper &>/dev/null; then
    for img in "${IMAGES[@]}"; do
        ENTRIES+=("image:$img")
    done
fi
if command -v mpvpaper &>/dev/null; then
    for vid in "${VIDEOS[@]}"; do
        ENTRIES+=("video:$vid")
    done
fi

# Nothing to do if no usable entries
if [[ ${#ENTRIES[@]} -eq 0 ]]; then
    exit 0
fi

apply_wallpaper() {
    local entry="$1"
    local type="${entry%%:*}"
    local file="${entry#*:}"

    if [[ "$type" == "video" ]]; then
        killall hyprpaper 2>/dev/null || true
        killall mpvpaper 2>/dev/null || true
        sleep 0.3
        local monitors
        monitors=$(hyprctl monitors -j | jq -r '.[].name')
        for mon in $monitors; do
            mpvpaper -o "no-audio loop hwdec=auto" "$mon" "$file" &
        done
    else
        if pgrep -x mpvpaper > /dev/null; then
            killall mpvpaper 2>/dev/null || true
            sleep 0.3
        fi
        if ! pgrep -x hyprpaper > /dev/null; then
            cat > "$HOME/.config/hypr/hyprpaper.conf" <<HYPR
# Auto-generated by Rainbeau
wallpaper {
    monitor =
    path = $file
    fit_mode = $FIT_MODE
}

splash = false
ipc = true
HYPR
            hyprpaper &
            sleep 0.5
        fi
        hyprctl hyprpaper wallpaper ",$file,$FIT_MODE" 2>/dev/null || true
    fi
}

while true; do
    PICK="${ENTRIES[$((RANDOM %% ${#ENTRIES[@]}))]}"
    apply_wallpaper "$PICK"
    # Single-entry themes (e.g. a lone Lottie/video wallpaper) still need
    # one apply to start mpvpaper/hyprpaper; after that there's nothing to
    # cycle to, so exit cleanly.
    if [[ ${#ENTRIES[@]} -le 1 ]]; then
        exit 0
    fi
    sleep "$INTERVAL"
done
`, theme.Name, theme.Wallpapers.CycleInterval, theme.Wallpapers.CycleInterval, theme.Wallpapers.FitMode, imageEntries, videoEntries), nil
}

type WallpaperSwitchGenerator struct{}

func (WallpaperSwitchGenerator) Name() string { return "Wallpaper Switch" }
func (WallpaperSwitchGenerator) OutputPath() string {
	return ".config/hypr/scripts/wallpaper-switch.sh"
}

func (WallpaperSwitchGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	return fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by Rainbeau — do not edit manually
# Theme: %s
# Switches to a random wallpaper (image or video) immediately.

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"
FIT_MODE="%s"

IMAGES=(
%s
)

VIDEOS=(
%s
)

# Build list of valid entries based on available tools
ENTRIES=()
if command -v hyprpaper &>/dev/null; then
    for img in "${IMAGES[@]}"; do
        ENTRIES+=("image:$img")
    done
fi
if command -v mpvpaper &>/dev/null; then
    for vid in "${VIDEOS[@]}"; do
        ENTRIES+=("video:$vid")
    done
fi

if [[ ${#ENTRIES[@]} -eq 0 ]]; then
    notify-send "Wallpaper Switch" "No wallpaper tools available (hyprpaper/mpvpaper)" 2>/dev/null || true
    exit 0
fi

PICK="${ENTRIES[$((RANDOM %% ${#ENTRIES[@]}))]}"
TYPE="${PICK%%:*}"
FILE="${PICK#*:}"

if [[ "$TYPE" == "video" ]]; then
    killall hyprpaper 2>/dev/null || true
    killall mpvpaper 2>/dev/null || true
    sleep 0.3
    monitors=$(hyprctl monitors -j | jq -r '.[].name')
    for mon in $monitors; do
        mpvpaper -o "no-audio loop hwdec=auto" "$mon" "$FILE" &
    done
else
    if pgrep -x mpvpaper > /dev/null; then
        killall mpvpaper 2>/dev/null || true
        sleep 0.3
    fi
    if ! pgrep -x hyprpaper > /dev/null; then
        cat > "$HOME/.config/hypr/hyprpaper.conf" <<HYPR
# Auto-generated by Rainbeau
wallpaper {
    monitor =
    path = $FILE
    fit_mode = $FIT_MODE
}

splash = false
ipc = true
HYPR
        hyprpaper &
        sleep 0.5
    fi
    hyprctl hyprpaper wallpaper ",$FILE,$FIT_MODE" 2>/dev/null || true
fi
`, theme.Name, theme.Wallpapers.FitMode, wallpaperArrayEntries(theme.Wallpapers.Images, false), wallpaperArrayEntries(theme.Wallpapers.Videos, true)), nil
}

type TemperatureScriptGenerator struct{}

func (TemperatureScriptGenerator) Name() string       { return "Temperature Script" }
func (TemperatureScriptGenerator) OutputPath() string { return ".config/hypr/scripts/temperature.sh" }

func (TemperatureScriptGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	sep := theme.Waybar.Separator
	return fmt.Sprintf(`#!/usr/bin/env bash
# Auto-generated by Rainbeau — do not edit manually
# Theme: %s
# CPU + GPU temperature for waybar

ICON=$'\uf2c9'
ICON_CRIT=$'\uf2c7'
SEP="<span color='%s'>%s</span>"
CRIT=80

get_cpu_temp() {
    # Try coretemp / k10temp first, then any hwmon with temp1_input
    for hwmon in /sys/class/hwmon/hwmon*; do
        name=$(cat "$hwmon/name" 2>/dev/null)
        case "$name" in
            coretemp|k10temp|zenpower)
                temp=$(cat "$hwmon/temp1_input" 2>/dev/null)
                if [[ -n "$temp" ]]; then
                    echo $((temp / 1000))
                    return
                fi
                ;;
        esac
    done
    # Fallback: first hwmon with temp1_input
    for hwmon in /sys/class/hwmon/hwmon*; do
        temp=$(cat "$hwmon/temp1_input" 2>/dev/null)
        if [[ -n "$temp" ]]; then
            echo $((temp / 1000))
            return
        fi
    done
}

get_gpu_temp() {
    # NVIDIA
    if command -v nvidia-smi &>/dev/null; then
        temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
        if [[ -n "$temp" ]]; then
            echo "$temp"
            return
        fi
    fi
    # AMD (amdgpu via hwmon)
    for hwmon in /sys/class/hwmon/hwmon*; do
        name=$(cat "$hwmon/name" 2>/dev/null)
        if [[ "$name" == "amdgpu" ]]; then
            temp=$(cat "$hwmon/temp1_input" 2>/dev/null)
            if [[ -n "$temp" ]]; then
                echo $((temp / 1000))
                return
            fi
        fi
    done
}

cpu=$(get_cpu_temp)
gpu=$(get_gpu_temp)

# Determine max temp for display
if [[ -n "$cpu" && -n "$gpu" ]]; then
    if (( cpu >= gpu )); then max=$cpu; else max=$gpu; fi
    tooltip="CPU: ${cpu}°C | GPU: ${gpu}°C"
elif [[ -n "$cpu" ]]; then
    max=$cpu
    tooltip="CPU: ${cpu}°C"
elif [[ -n "$gpu" ]]; then
    max=$gpu
    tooltip="GPU: ${gpu}°C"
else
    printf '{"text": "%%s N/A %%s", "tooltip": "No temperature sensors found", "class": "normal"}\n' "$ICON" "$SEP"
    exit 0
fi

if (( max >= CRIT )); then
    icon=$ICON_CRIT
    class="critical"
else
    icon=$ICON
    class="normal"
fi

printf '{"text": "%%s %%s°C %%s", "tooltip": "%%s", "class": "%%s"}\n' "$icon" "$max" "$SEP" "$tooltip" "$class"
`, theme.Name, c.Accent1, sep), nil
}

type HyprlockGenerator struct{}

func (HyprlockGenerator) Name() string       { return "Hyprlock" }
func (HyprlockGenerator) OutputPath() string { return ".config/hypr/hyprlock.conf" }
func (HyprlockGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	font := theme.Font
	backgroundBlock := buildSolidHyprlockBackground(c.Bg0)
	if len(theme.Wallpapers.Images) > 0 {
		backgroundBlock = buildImageHyprlockBackground(theme.Wallpapers.Images, p.IsLight)
	}
	return fmt.Sprintf(`# Auto-generated by Rainbeau — do not edit manually
# Theme: %s

auth:fingerprint:enabled = true

%s

input-field {
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(%s)
    inner_color = rgb(%s)
    font_color = rgb(%s)
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    hide_input = false
    check_color = rgb(%s)
    fail_color = rgb(%s)
    fail_text = <i>$FAIL</i>
    capslock_color = rgb(%s)
    position = 0, -80
    halign = center
    valign = center
    font_family = %s
}

label {
    text = $TIME
    color = rgb(%s)
    font_size = 64
    font_family = %s
    shadow_passes = 0
    position = 0, 80
    halign = center
    valign = center
}

label {
    text = $USER
    color = rgb(%s)
    font_size = 16
    font_family = %s
    shadow_passes = 0
    position = 0, -20
    halign = center
    valign = center
}

label {
    text = $FPRINTPROMPT
    color = rgb(%s)
    font_size = 14
    font_family = %s
    shadow_passes = 0
    position = 0, -150
    halign = center
    valign = center
}
`, theme.Name, backgroundBlock, stripHash(p.Border), stripHash(c.Bg1), stripHash(p.Text), stripHash(p.Green), stripHash(p.Red), stripHash(p.Accent2), font.Family, stripHash(p.Text), font.Family, stripHash(p.Text), font.Family, stripHash(p.Accent1), font.Family), nil
}

type GtkCSSGenerator struct{}

func (GtkCSSGenerator) Name() string       { return "GTK CSS" }
func (GtkCSSGenerator) OutputPath() string { return ".config/gtk-3.0/gtk.css" }
func (GtkCSSGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	return fmt.Sprintf(`/* Auto-generated by Rainbeau — do not edit manually */
/* Theme: %s */

window, dialog {
    background-color: %s;
    color: %s;
}

headerbar, .titlebar {
    background-color: %s;
    color: %s;
    border-bottom: 1px solid %s;
}

headerbar:backdrop, .titlebar:backdrop {
    background-color: %s;
    color: %s;
}

button {
    background-color: %s;
    color: %s;
    border: 1px solid %s;
    border-radius: 4px;
}

button:hover {
    background-color: %s;
    border-color: %s;
}

button:active, button:checked {
    background-color: %s;
    color: %s;
}

scale trough {
    background-color: %s;
    border-radius: 4px;
}

scale highlight {
    background-color: %s;
    border-radius: 4px;
}

scale slider {
    background-color: %s;
    border: 1px solid %s;
    border-radius: 50%%;
}

row, list row {
    background-color: %s;
    color: %s;
}

row:hover, list row:hover {
    background-color: %s;
}

row:selected, list row:selected {
    background-color: %s;
    color: %s;
}

notebook tab {
    background-color: %s;
    color: %s;
    border: 1px solid %s;
}

notebook tab:checked {
    background-color: %s;
    color: %s;
    border-bottom-color: %s;
}

entry {
    background-color: %s;
    color: %s;
    border: 1px solid %s;
    border-radius: 4px;
}

entry:focus {
    border-color: %s;
}

combobox button {
    background-color: %s;
    color: %s;
}

scrollbar slider {
    background-color: %s;
    border-radius: 4px;
}

scrollbar slider:hover {
    background-color: %s;
}

menu, popover {
    background-color: %s;
    color: %s;
    border: 1px solid %s;
}

menu menuitem:hover {
    background-color: %s;
    color: %s;
}

tooltip, tooltip.background {
    background-color: %s;
    color: %s;
    border: 1px solid %s;
    border-radius: 4px;
}

/* Treeview (blueman, file pickers, etc.) */
treeview, treeview.view {
    background-color: %s;
    color: %s;
}

treeview:selected, treeview.view:selected,
treeview row:selected, treeview.view row:selected {
    background-color: %s;
    color: %s;
}

treeview:hover, treeview.view:hover {
    background-color: %s;
}

treeview header button {
    background-color: %s;
    color: %s;
    border-bottom: 1px solid %s;
}

/* Global selection override */
*:selected {
    background-color: %s;
    color: %s;
}

*:selected:focus {
    background-color: %s;
    color: %s;
}

/* Toolbar / action bar */
toolbar, .toolbar, actionbar {
    background-color: %s;
    border-bottom: 1px solid %s;
}

/* Statusbar */
statusbar {
    background-color: %s;
    color: %s;
}

/* Switch toggle (bluetooth toggle) */
switch {
    background-color: %s;
    border: 1px solid %s;
    border-radius: 14px;
}

switch:checked {
    background-color: %s;
}

switch slider {
    background-color: %s;
    border-radius: 50%%;
}
`, theme.Name, c.Bg0, p.Text, c.Bg1, p.Text, c.Bg2, c.Bg0, p.Inactive, c.Bg2, p.Text, p.Inactive, c.Bg3, p.Border, p.Border, c.Bg0, c.Bg2, p.Border, p.Accent1, p.Accent2, c.Bg0, p.Text, c.Bg1, p.SelectionBg, p.SelectionFg, c.Bg0, p.TextDim, c.Bg2, c.Bg1, p.Accent1, p.Border, c.Bg1, p.Text, p.Inactive, p.Border, c.Bg1, p.Text, p.Inactive, p.Border, c.Bg1, p.Text, c.Bg2, p.SelectionBg, p.SelectionFg, c.Bg1, p.Text, p.Border, c.Bg0, p.Text, p.SelectionBg, p.SelectionFg, c.Bg1, c.Bg1, p.TextDim, c.Bg2, p.SelectionBg, p.SelectionFg, p.SelectionBg, p.SelectionFg, c.Bg1, c.Bg2, c.Bg0, p.TextDim, c.Bg2, p.Inactive, p.Border, p.Text), nil
}

func wallpaperArrayEntries(paths []string, allowAbsolute bool) string {
	entries := make([]string, 0, len(paths))
	for _, path := range paths {
		if allowAbsolute && filepath.IsAbs(path) {
			entries = append(entries, fmt.Sprintf(`  "%s"`, path))
		} else {
			entries = append(entries, fmt.Sprintf(`  "$WALLPAPER_DIR/%s"`, path))
		}
	}
	return strings.Join(entries, "\n")
}

func buildImageHyprlockBackground(images []string, isLight bool) string {
	pick := images[rand.Intn(len(images))]
	brightness := "0.6"
	if isLight {
		brightness = "1.2"
	}
	return fmt.Sprintf(`background {
    path = ~/.config/hypr/wallpapers/%s
    blur_passes = 3
    blur_size = 6
    brightness = %s
}
`, pick, brightness)
}

func buildSolidHyprlockBackground(bg0 string) string {
	return fmt.Sprintf(`background {
    path =
    color = rgb(%s)
}
`, stripHash(bg0))
}

func stripHash(hex string) string {
	return strings.TrimPrefix(hex, "#")
}
