package generators

import (
	"fmt"
	"strings"

	rainbeau "github.com/AlexMacocian/rainbeau/internal"
)

type WaybarConfigGenerator struct{}

func (WaybarConfigGenerator) Name() string       { return "Waybar Config" }
func (WaybarConfigGenerator) OutputPath() string { return ".config/waybar/config.jsonc" }
func (WaybarConfigGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	var iconEntries []string
	for i, label := range theme.Waybar.WorkspaceLabels {
		iconEntries = append(iconEntries, fmt.Sprintf(`      "%d": "%s"`, i+1, label))
	}

	return replaceTokens(`// Auto-generated by Rainbeau — do not edit manually
// Theme: @@theme@@
{
  "layer": "top",
  "height": @@height@@,
  "spacing": 0,

  "hyprland/workspaces": {
    "format": "{icon}",
    "on-click": "activate",
    "format-icons": {
@@formatIcons@@
    }
  },

  "hyprland/window": {
    "max-length": 40,
    "separate-outputs": true
  },

  "modules-left": [
    "hyprland/workspaces",
    "hyprland/submap"
  ],

  "modules-center": [
    "clock"
  ],

  "modules-right": [
    "custom/recording",
    "pulseaudio",
    "network",
    "custom/bluetooth",
    "cpu",
    "memory",
    "custom/gpu",
    "disk",
    "custom/temperature",
    "backlight",
    "battery",
    "power-profiles-daemon",
    "tray",
    "custom/updates",
    "custom/power"
  ],

  "custom/bluetooth": {
    "exec": "~/.config/hypr/scripts/bluetooth-status.sh",
    "return-type": "json",
    "interval": 5,
    "on-click": "kitty --title bluetuith --override background_opacity=0.95 -e bluetuith",
    "tooltip": true
  },

  "custom/updates": {
    "exec": "~/.config/hypr/scripts/update-check.sh",
    "return-type": "json",
    "interval": 600,
    "signal": 8,
    "on-click": "kitty --title updates --override background_opacity=0.95 -e bash -c 'if command -v paru &>/dev/null; then paru -Syu; elif command -v yay &>/dev/null; then yay -Syu; else sudo pacman -Syu; fi; echo; echo Done. Press enter to close.; read; pkill -RTMIN+8 waybar'",
    "tooltip": true
  },

  "clock": {
    "format": "\uf017 {:%H:%M  @@sep@@  %a, %b %d}",
    "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
    "format-alt": "\uf017 {:%Y-%m-%d  %H:%M:%S}"
  },

  "cpu": {
    "format": "\uf2db {usage}% <span color='@@accent1@@'>@@sep@@</span>",
    "tooltip": true,
    "interval": 2
  },

  "memory": {
    "format": "\uf233 {}% <span color='@@accent1@@'>@@sep@@</span>"
  },

  "custom/gpu": {
    "exec": "~/.config/hypr/scripts/gpu-usage.sh",
    "return-type": "json",
    "interval": 5,
    "tooltip": true
  },

  "disk": {
    "format": "\uf0a0 {percentage_used}% <span color='@@accent1@@'>@@sep@@</span>",
    "tooltip-format": "{used} / {total} on {path}",
    "path": "/",
    "interval": 30
  },

  "custom/temperature": {
    "exec": "~/.config/hypr/scripts/temperature.sh",
    "return-type": "json",
    "interval": 5,
    "tooltip": true
  },

  "backlight": {
    "format": "\uf185 {percent}% <span color='@@accent1@@'>@@sep@@</span>"
  },

  "battery": {
    "states": {
      "warning": 30,
      "critical": 15
    },
    "format": "\uf240 {capacity}% <span color='@@accent1@@'>@@sep@@</span>",
    "format-full": "\uf240 {capacity}% <span color='@@accent1@@'>@@sep@@</span>",
    "format-charging": "\uf0e7 {capacity}% <span color='@@accent1@@'>@@sep@@</span>",
    "format-plugged": "\uf1e6 {capacity}% <span color='@@accent1@@'>@@sep@@</span>",
    "format-alt": "\uf240 {time} <span color='@@accent1@@'>@@sep@@</span>"
  },

  "power-profiles-daemon": {
    "format": "\uf0e7 <span color='@@accent1@@'>@@sep@@</span>",
    "tooltip-format": "Power profile: {profile}\nDriver: {driver}",
    "tooltip": true
  },

  "network": {
    "format-wifi": "\uf1eb {essid} <span color='@@accent1@@'>@@sep@@</span>",
    "format-ethernet": "\uf0e8 {ipaddr} <span color='@@accent1@@'>@@sep@@</span>",
    "tooltip-format": "{ifname} via {gwaddr}\n{ipaddr}/{cidr}",
    "format-linked": "\uf0e8 {ifname} <span color='@@accent1@@'>@@sep@@</span>",
    "format-disconnected": "\uf071 Offline <span color='@@accent1@@'>@@sep@@</span>",
    "on-click": "kitty --title nmtui --override background_opacity=0.95 -e nmtui"
  },

  "pulseaudio": {
    "format": "\uf028 {volume}% <span color='@@accent1@@'>@@sep@@</span>",
    "scroll-step": 2,
    "format-bluetooth": "\uf294 {volume}% <span color='@@accent1@@'>@@sep@@</span>",
    "format-bluetooth-muted": "\uf294 muted <span color='@@accent1@@'>@@sep@@</span>",
    "format-muted": "\uf026 muted <span color='@@accent1@@'>@@sep@@</span>",
    "on-click": "kitty --title pulsemixer --override background_opacity=0.95 -e pulsemixer"
  },

  "tray": {
    "icon-size": 16,
    "spacing": 8
  },

  "custom/recording": {
    "exec": "~/.config/hypr/scripts/recording-status.sh",
    "return-type": "json",
    "interval": "once",
    "signal": 9,
    "tooltip": true
  },

  "custom/power": {
    "format": "\uf011",
    "tooltip": false,
    "on-click": "~/.config/hypr/scripts/power-menu.sh"
  }
}
`, map[string]string{
		"theme":       theme.Name,
		"height":      fmt.Sprint(theme.Waybar.Height),
		"formatIcons": strings.Join(iconEntries, ",\n"),
		"sep":         theme.Waybar.Separator,
		"accent1":     theme.Colors.Accent1,
	}), nil
}

type WaybarStyleGenerator struct{}

func (WaybarStyleGenerator) Name() string       { return "Waybar Style" }
func (WaybarStyleGenerator) OutputPath() string { return ".config/waybar/style.css" }
func (WaybarStyleGenerator) Generate(theme *rainbeau.Theme, wallpapersDir string) (string, error) {
	c := theme.Colors
	p := rainbeau.ResolvePalette(theme)
	w := theme.Waybar
	font := theme.Font
	fontFamily := fmt.Sprintf(`"%s"`, font.Family)
	if len(font.Fallback) > 0 {
		var fallbacks []string
		for _, fallback := range font.Fallback {
			if strings.Contains(fallback, " ") {
				fallback = fmt.Sprintf(`"%s"`, fallback)
			}
			fallbacks = append(fallbacks, fallback)
		}
		fontFamily += ", " + strings.Join(fallbacks, ", ")
	}

	return replaceTokens(`/* Auto-generated by Rainbeau — do not edit manually */
/* Theme: @@theme@@ */

* {
    font-family: @@fontFamily@@;
    font-size: @@fontSize@@px;
}

window#waybar {
    background-color: @@bg0Rgba@@;
    border-bottom: @@borderWidth@@px solid @@borderRgba@@;
    color: @@text@@;
    transition-property: background-color;
    transition-duration: 0.4s;
}

window#waybar.hidden {
    opacity: 0.2;
}

button {
    box-shadow: inset 0 -2px transparent;
    border: none;
    border-radius: 0;
}

button:hover {
    background: inherit;
    box-shadow: inset 0 -2px @@border@@;
}

#workspaces button {
    padding: 0 6px;
    background-color: transparent;
    color: @@textDim@@;
    font-weight: bold;
    font-size: 11px;
}

#workspaces button:hover {
    background: @@border12@@;
    color: @@text@@;
}

#workspaces button.active {
    background-color: @@border18@@;
    color: @@accent1@@;
    box-shadow: inset 0 -2px @@border@@;
}

#workspaces button.urgent {
    background-color: @@red40@@;
    color: @@text@@;
}

#clock,
#battery,
#cpu,
#memory,
#disk,
#custom-temperature,
#backlight,
#network,
#pulseaudio,
#wireplumber,
#custom-media,
#tray,
#mode,
#idle_inhibitor,
#scratchpad,
#power-profiles-daemon,
#custom-power {
    padding: 0 8px;
    color: @@text@@;
    background-color: transparent;
}

#cpu,
#memory,
#disk,
#custom-temperature,
#backlight,
#network,
#pulseaudio,
#battery,
#power-profiles-daemon,
#custom-gpu,
#custom-bluetooth,
#custom-updates,
#custom-power {
    padding: 0 4px;
    min-width: 20px;
}

#window,
#workspaces {
    margin: 0 4px;
}

.modules-left > widget:first-child > #workspaces {
    margin-left: 0;
}

.modules-right > widget:last-child > #workspaces {
    margin-right: 0;
}

#clock {
    font-weight: bold;
    font-size: @@fontSize@@px;
    color: @@textDim@@;
    padding: 0 16px;
}

#clock:hover {
    color: @@accent1@@;
}

#battery { color: @@text@@; }
#battery.charging, #battery.plugged { color: @@green@@; }

@keyframes blink-scarlet {
    to {
        background-color: @@red50@@;
        color: @@text@@;
    }
}

#battery.critical:not(.charging) {
    background-color: @@red25@@;
    color: @@text@@;
    animation-name: blink-scarlet;
    animation-duration: 0.8s;
    animation-timing-function: steps(12);
    animation-iteration-count: infinite;
    animation-direction: alternate;
}

#battery.warning { color: @@accent2@@; }

#power-profiles-daemon { color: @@textDim@@; }
#power-profiles-daemon.performance { color: @@red@@; }
#power-profiles-daemon.balanced { color: @@textDim@@; }
#power-profiles-daemon.power-saver { color: @@green@@; }

#cpu { color: @@textDim@@; }
#memory { color: @@textDim@@; }
#custom-temperature { color: @@textDim@@; }
#custom-temperature.critical { color: @@red@@; }
#backlight { color: @@textDim@@; }
#network { color: @@textDim@@; }
#network.disconnected { color: @@red@@; }

#network:hover,
#pulseaudio:hover,
#cpu:hover,
#memory:hover,
#disk:hover,
#custom-temperature:hover,
#custom-temperature:hover *,
#backlight:hover,
#battery:hover,
#power-profiles-daemon:hover,
#custom-power:hover,
#custom-power:hover *,
#custom-bluetooth:hover,
#custom-bluetooth:hover *,
#custom-bluetooth.connected:hover,
#custom-bluetooth.connected:hover *,
#custom-bluetooth.on:hover,
#custom-bluetooth.on:hover *,
#custom-bluetooth.off:hover,
#custom-bluetooth.off:hover *,
#custom-updates:hover,
#custom-updates:hover *,
#custom-updates.pending:hover,
#custom-updates.pending:hover *,
#custom-gpu:hover,
#custom-gpu:hover * {
    color: @@accent1@@;
}

#custom-gpu { color: @@textDim@@; }

#custom-bluetooth { color: @@textDim@@; }
#custom-bluetooth.connected { color: @@textDim@@; }
#custom-bluetooth.off { color: @@inactive@@; }

#custom-updates { color: @@textDim@@; }
#custom-updates.pending { color: @@accent1@@; }
#custom-updates.updated { color: @@inactive@@; }
#disk { color: @@textDim@@; }

#pulseaudio { color: @@textDim@@; }
#pulseaudio.muted { color: @@inactive@@; }

#tray { padding: 0 6px; }
#tray > .passive { -gtk-icon-effect: dim; }
#tray > .needs-attention {
    -gtk-icon-effect: highlight;
    background-color: @@red30@@;
}

#custom-power {
    color: @@textDim@@;
    padding: 0 10px 0 6px;
}

#custom-power:hover { color: @@red@@; }

#custom-recording {
    color: @@red@@;
    font-weight: bold;
    padding: 0 6px;
    animation: blink-recording 1s steps(2) infinite;
}

#custom-recording.off {
    color: transparent;
    animation: none;
    padding: 0;
    margin: 0;
    min-width: 0;
}

@keyframes blink-recording { 50% { opacity: 0.3; } }

#idle_inhibitor { color: @@inactive@@; }
#idle_inhibitor.activated { color: @@accent1@@; }

#submap {
    color: @@accent2@@;
    font-weight: bold;
}

tooltip {
    background-color: @@bg1Tooltip@@;
    border: 1px solid @@border50@@;
    border-radius: 4px;
    color: @@text@@;
}

tooltip label {
    color: @@text@@;
}
`, map[string]string{
		"theme":       theme.Name,
		"fontFamily":  fontFamily,
		"fontSize":    fmt.Sprint(font.Size),
		"bg0Rgba":     rainbeau.ToCSSRgba(c.Bg0, w.Opacity),
		"borderWidth": fmt.Sprint(w.BorderWidth),
		"borderRgba":  rainbeau.ToCSSRgba(p.Border, 0.6),
		"text":        p.Text,
		"border":      p.Border,
		"textDim":     p.TextDim,
		"border12":    rainbeau.ToCSSRgba(p.Border, 0.12),
		"border18":    rainbeau.ToCSSRgba(p.Border, 0.18),
		"accent1":     p.Accent1,
		"accent2":     p.Accent2,
		"red":         p.Red,
		"red25":       rainbeau.ToCSSRgba(p.Red, 0.25),
		"red30":       rainbeau.ToCSSRgba(p.Red, 0.3),
		"red40":       rainbeau.ToCSSRgba(p.Red, 0.4),
		"red50":       rainbeau.ToCSSRgba(p.Red, 0.5),
		"green":       p.Green,
		"inactive":    p.Inactive,
		"bg1Tooltip":  rainbeau.ToCSSRgba(c.Bg1, 0.95),
		"border50":    rainbeau.ToCSSRgba(p.Border, 0.5),
	}), nil
}

func replaceTokens(template string, values map[string]string) string {
	replacerArgs := make([]string, 0, len(values)*2)
	for key, value := range values {
		replacerArgs = append(replacerArgs, "@@"+key+"@@", value)
	}
	return strings.NewReplacer(replacerArgs...).Replace(template)
}
